const CONFIG = {
  ICON_URL: "https://openweathermap.org/img/wn",
  MAX_HISTORY: 10,
  TOAST_DURATION: 4000,
  SUGGESTED_CITIES: [
    "Hà Nội",
    "TP. Hồ Chí Minh",
    "Đà Nẵng",
    "Cần Thơ",
    "Hải Phòng",
    "Singapore",
    "Bangkok",
    "Tokyo",
  ],
  CITY_ALIASES: {
    "tp. hồ chí minh": "Ho Chi Minh City",
    "tp hồ chí minh": "Ho Chi Minh City",
    "hồ chí minh": "Ho Chi Minh City",
    tphcm: "Ho Chi Minh City",
    "sài gòn": "Ho Chi Minh City",
    "hà nội": "Hanoi",
    "hà nôi": "Hanoi",
    "đà nẵng": "Da Nang",
    "đà nẳng": "Da Nang",
    "cần thơ": "Can Tho",
    "hải phòng": "Hai Phong",
    huế: "Hue",
    "nha trang": "Nha Trang",
    "vũng tàu": "Vung Tau",
    "đà lạt": "Da Lat",
    "buôn ma thuột": "Buon Ma Thuot",
    "quy nhơn": "Quy Nhon",
  },
};
